version: "3.9"

services:
  database:
    image: postgres:14
    ports:
      - 5432:5432
    env_file: .env
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - /path/to/redis-persistence:/bitnami/redis/data
    depends_on:
      - database
