# Generated by Django 4.0.4 on 2022-05-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_city', models.IntegerField(verbose_name='Идентификатор города')),
                ('name', models.CharField(max_length=20, verbose_name='Название города')),
                ('timezone', models.IntegerField(verbose_name='Сдвиг в секундах от UTC')),
                ('coord_lon', models.FloatField(verbose_name='Географическое положение города, долгота')),
                ('coord_lat', models.FloatField(verbose_name='Географическое положение города, широта')),
                ('weather_id', models.IntegerField(verbose_name='Идентификатор погодных условий')),
                ('weather_main', models.CharField(max_length=50, verbose_name='Группа погодных параметров')),
                ('weather_description', models.CharField(max_length=255, verbose_name='Погодные условия в группе')),
                ('weather_icon', models.CharField(max_length=20, verbose_name='Идентификатор значка погоды')),
                ('base', models.CharField(max_length=50, verbose_name='Внутренний параметр')),
                ('main_temp', models.FloatField(verbose_name='Температура')),
                ('main_feels_like', models.FloatField(verbose_name='Человеческое восприятие температуры ')),
                ('main_temp_min', models.FloatField(verbose_name='Минимальная температура на данный момент')),
                ('main_temp_max', models.FloatField(verbose_name='Максимальная температура на данный момент')),
                ('main_pressure', models.IntegerField(verbose_name='Атмосферное давление гПа')),
                ('main_humidity', models.IntegerField(verbose_name='Влажность, %')),
                ('visibility', models.IntegerField(verbose_name='Видимость, метр. Максимальное значение видимости 10км')),
                ('wind_speed', models.FloatField(verbose_name='Скорость ветра метр/сек')),
                ('wind_deg', models.FloatField(verbose_name='Направление ветра, градусы')),
                ('wind_gust', models.FloatField(verbose_name='Порыв ветра. метр/сек')),
                ('clouds_all', models.IntegerField(verbose_name='Облачность, %')),
                ('dt', models.IntegerField(verbose_name='Время расчета данных, unix, UTC')),
                ('sys_country', models.CharField(max_length=10, verbose_name='Код страны')),
                ('sys_sunrise', models.IntegerField(verbose_name='Время восхода солнца, unix, UTC')),
                ('sys_sunset', models.IntegerField(verbose_name='Время заката, unix, UTC')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
