# Generated by Django 4.0.4 on 2022-05-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='wind_gust',
            field=models.FloatField(blank=True, null=True, verbose_name='Порыв ветра. метр/сек'),
        ),
    ]
