# Generated by Django 4.0.4 on 2022-05-18 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weather', '0002_alter_city_wind_gust'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicity_send_email', models.CharField(choices=[('1', '1 hours'), ('3', '3 hours'), ('6', '6 hours'), ('12', '12 hours')], default='6', max_length=2, verbose_name='Периодичность отправить письмо')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.city')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_city', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
