# Generated by Django 4.0.4 on 2022-05-18 12:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weather', '0003_subscriptioncity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptioncity',
            unique_together={('owner', 'city')},
        ),
    ]
