# Generated by Django 3.2.13 on 2022-05-28 16:00

from django.db import migrations
from django.conf import settings


def create_interval_schedule(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    IntervalSchedule = apps.get_model('django_celery_beat', 'IntervalSchedule')
    for time in settings.TIME_LIST:
        IntervalSchedule.objects.create(
            every=time,
            period='hours',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_subscriptioncity_periodic_task'),
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
    ]

    operations = [migrations.RunPython(create_interval_schedule)]
