# Generated by Django 3.2.13 on 2022-08-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_auto_20220528_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='main_feels_like',
            field=models.FloatField(verbose_name='Человеческое восприятие температуры'),
        ),
    ]
